dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-09/run.sh |
  bash
notifications:
  slack:
    secure: VPI/tE4HDuYRST4qOx1My+tMtnyF2Gx/FJegF0TfUKnzzwlt8DEzpuyIF2j3KTRNRL46Jt71b86dNiAK40HHGaQWpPt88oSCIlmC0Ai/YgsIG/0JQkk79jvGwNQA37os5umBkuYYD4OCc1JQtJodtfeYRMpIWCSpz8XlvJxcPS/DbrkWOFkxCd7U+1RXUb0lqLMvY3MUOo4f7mr8ymzeTb0Buu9BqomPJu1ey1i2aNIGeO7YKqT12N4RQ9tU/1jbuYaqt45aeiJSGOUkEiLv4AtMCm6C1VBpKYSy2bVDc+g+ADQW0hEhXSA4va605Hsox0HG0x/z0XC0Jz2wjGup9Yn3FUkw1NAobLJe1Z9z4aqxY3T2FUjd9Py8WNlMFZtj3fbNB0R//0nfVK1W1WOQfMY4PCt0cZHiueXmXw26M+WAHcUBtvKajpCSsGaAGsgLV3vGqxAky/KOb3xpYoowgVtQoQzZ2eOqRDhlIr3/VxkOFipdi4u39kZ7+ZvXij3fl5IsX6LDIBcHLa/ghoTXqx8E+AE0q5s85mfysRa+lNPMWwdVU6QP2/ooBAEUBPebtpdPsWVrblJiAIsUC2FRm2ng1yF1FCtzpSxxAdxJedzwSxSa0UJsXicZGj+lz8l0Ln+HKWWKe6Jxw37kGMg51f071Tm21mpt5nPi4edKCso=
