dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-09/run.sh | bash
notification:
  slack:
    rooms:
      secure: kUTS0LGYpmmFvPZmxoKy3Wg6SAeNhvkTPvVRNdszSB0nf/d0xtM2nyy7nv+lo6Gw/ph1KXDGU0xUtTns4rfZtNVDAghfcS4/8IueaPCBsnkeq9gTiYr2BQgdQkrH/4WgqfKXAFEJwsDpK/bjPUKvz68FjcdK2WxnRx48Uyz7S2WLCDcm/Dvz3m/I3IlYPPblcyvlNfzcmpEqU1uaerdMWGoQUuTt6S/DfbRICJ8We0ONIS9PhXYH+6rIHvdy0CmlCAXGjq7bfGnniRM7lUM2H23COjtGpOMTAGehPCMfgiKmW/NPL1NPMQAT4c/hUEhmH6IvfORsbwqPTaZWJZFVZN5qDIUqGVuV7XpZD2sYsk4L13yiCbEzyvg3LeiQeGM8JbBqCknUYEGS3ZktHa6d1uRTubnGnbTCGAZviD1640vJfkxO+qq930/1xtt0sSw/ZRq+glmTFX/kjN+zp84Ao+K9bAySzVLez89dwKv4DNMYlisneuQ92ExtALJrY1gGKOadIIgjsegCu3EXRircDvFG6U0hx/Rl/q749Zwa8sk7aetfSgxEQEl6r5MkenMAGRghzX+mVtMHF9bvGnbCTIpxMW4fN9+gyXskuXveAfwawVoWx687J7OfSuh7/YtSCqJ9IHk7UmTEn96fDr+XcCYiYXHMjOfDQKxwlqAO7ww=
